### ISSUE TITLE
This website should be archived and taken offline by it's owners

### ISSUE THREAD

**Issue by RealDrGordonFreeman** [lamby/whydoesaptnotusehttps.com#13]
This website (whydoesaptnotusehttps.com) is providing misleading information to the public.

See here: https://blog.packagecloud.io/eng/2018/02/21/attacks-against-secure-apt-repositories/

**Comment by lamby** [comment]
If anything, the content could be updated. But the packagecloud rebuttal does not result in this site needing to be taken offline.

**Comment by RealDrGordonFreeman** [comment]
You have personally and intensively argued against package privacy, while claiming signatures are adequate.

People do not want their ISP or various three letter agencies to easily know which packages are being downloaded.

While not impossible, TLS with a good cipher suite makes it **very** difficult for local or interstate monitoring linkages to learn of which exact packages are being transferred.

See the Snowden Archive for further information.

**Comment by lamby** [comment]
> You have personally and intensively argued 

I have not. This is a descriptive site ("why apt does not.."), not an evagalism one ("why apt should not").

**Comment by RealDrGordonFreeman** [comment]
Will you not agree TLS for apt greatly improves package privacy?

**Comment by lamby** [comment]
This site is not about my opinions...
